[project]
name = "Storyboard-LLM"
version = "v1.0.3"               
description = "将小说章节转换为影视分镜脚本的ComfyUI插件 "
license = {file = "License"} 
requires-python = ">=3.13"     

[project.urls]
Repository = "https://github.com/Lbunc/ComfyUI-Storyboard-LLM" 

[tool.comfy]
PublisherId = "lbunc"     
DisplayName = "Storyboard-LLM" 